### ISSUE TITLE
Fehler mit SDR: doppelt aufgeführte Flächenmasse

### ISSUE THREAD

**Issue by edigonzales** [sogis/avgbs2mtab-web-service#5]
E-Mail NF-Geometer:

"Bei der Anwendung von avgbs2mtab mit SDR entsteht im angefügten Fall ein falsches Resultat. Siehe dazu das .xml, das resultierende .xlsx und der Mut.-plan mit der korrigierten Tabelle."

[sdr.zip](https://github.com/sogis/avgbs2mtab-web-service/files/2723180/sdr.zip)

**Comment by EchoCharlie85** [comment]
Gefixt mit Commit e0b35a9c89798a54968f7d90e55e020995d8b3f9
